### ISSUE TITLE
Add prominent "Submit your paper" buttons to the front and CFP pages

### ISSUE THREAD

**Issue by tompollard** [ahli-org/chil-website#102]
To encourage paper submissions (and to make it easy for people to find the [submission portal](https://openreview.net/group?id=chilconference.org/CHIL/2022/Conference)) I think it would be good to add a prominent "Submit your paper" button to the front page of https://www.chilconference.org/.

The link should also be added prominently at: https://www.chilconference.org/call-for-papers.html

**Comment by tnaumann** [comment]
I've added a button to the CFP page. @tompollard - can you confirm this is what you had in mind?

@briangow / @kperros / @corcra - can you add a similar button to the Home page between "CHIL 2022" and "Contact US"?

**Comment by tompollard** [comment]
thanks @tnaumann, looks good to me!

**Comment by briangow** [comment]
This was resolved with #113
