### ISSUE TITLE
Add 5th tutorial speaker info

### ISSUE THREAD

**Issue by tasmie** [ahli-org/chil-website#131]
Add to Yin's info to the site: https://docs.google.com/document/d/1nAT6_y9oDNBMq1SlLS5bMz1wfZqK19boldzJKEgtmWI/edit 

Also add headshots if possible for all speakers: https://drive.google.com/drive/folders/1qCjgA8z97HoITZLJD-rj5mb8kV91tKfn?usp=sharing

**Comment by kperros** [comment]
Note: #134 PR does not link speaker headshots in the tutorials' page.
