### ISSUE TITLE
Add keynote speaker titles & abstracts

### ISSUE THREAD

**Issue by tasmie** [ahli-org/chil-website#137]
https://docs.google.com/document/d/103w9q7N3qz6qEz_BgyRROA7G5mg7u3rOm6yvMFy-eXI/edit#

**Comment by briangow** [comment]
The available keynote speaker title & abstracts have been added. Will leave this open until the remaining get added and are updated.

**Comment by tasmie** [comment]
@briangow Danielle's title and abstract are now available: 

Title: 
Understanding Heterogeneity as a Route to Understanding Health

Abstract: 
Machine learning presents an opportunity to understand the patient journey over high dimensional data in the clinical context. This is aligned to one of the foundational issues of machine learning for healthcare:  how do you represent a patient state. Improving state representations allows us to (i) visualise/cluster deteriorating patients, (ii) understand the patient journey and thus heterogeneous pathways to improvement or clinical deterioration which encompasses different data modalities; and thus (iii) more quickly identify situations for intervention. In this talk, I present motivating examples of understanding heterogeneity as a route towards understanding health and personalising healthcare interventions.
