### ISSUE TITLE
Import Markup from flask error and workaround

### ISSUE THREAD

**Issue by briangow** [ahli-org/chil-website#200]
Currently when setting up an environment with `requirements.txt` and python 3.9.10, I get the following error when doing `make run`:

```
export FLASK_DEBUG=True; export FLASK_DEVELOPMENT=True; python3 main.py sitedata/
Traceback (most recent call last):
  File "/Users/briangow/Dropbox (MIT)/MIT/conferences/chil2024/chil-website/main.py", line 11, in <module>
    from flaskext.markdown import Markdown
  File "/Users/briangow/Dropbox (MIT)/MIT/conferences/chil2024/chil-website/env/lib/python3.9/site-packages/flaskext/markdown.py", line 32, in <module>
    from flask import Markup
ImportError: cannot import name 'Markup' from 'flask' (/Users/briangow/Dropbox (MIT)/MIT/conferences/chil2024/chil-website/env/lib/python3.9/site-packages/flask/__init__.py)
make: *** [run] Error 1
```
It appears that `flaskext` has not been updated to import `Markup` from the `markupsafe` package. As mentioned in this similar issue, one should use `from markupsafe import Markup` now instead: https://stackoverflow.com/questions/73834946/importerror-cannot-import-name-markup-from-jinja2-in-flask . 

To resolve the above error, edit "/Users/briangow/Dropbox (MIT)/MIT/conferences/chil2024/chil-website/env/lib/python3.9/site-packages/flaskext/markdown.py" from:
`from flask import Markup`
to
`from markupsafe import Markup`

**Comment by tompollard** [comment]
For local builds, I assume the expectation is that you should be using https://github.com/ahli-org/chil-website/blob/main/requirements-dev.txt, though I'm not sure this will change anything.

The solution is probably to pin versions in the requirements files, rather than editing packages inside your installation directory. Side note, but I'm not sure we need two requirements files? One is probably enough!

**Comment by briangow** [comment]
@tompollard , assuming you don't get the error above could you share your python version and the package versions from `requirements.txt` that you're running? I haven't gotten that error to go away by using newer / older versions of python and flask. 

Regarding `requriements-dev.txt` I don't think we need the `chat/requirements.txt` packages since we are no longer using RocketChat.

**Comment by tompollard** [comment]
It's been a while since I've worked on the site so I don't have a local environment to copy. I had a quick play around and this seems to work though:

```
blinker==1.6.3
click==8.1.7
Flask==2.1.0
Flask-Markdown==0.3
Frozen-Flask==0.18
itsdangerous==2.1.2
Jinja2==3.1.2
Markdown==3.5
MarkupSafe==2.1.3
PyYAML==6.0.1
tqdm==4.66.1
Werkzeug==2.0.3
```

**Comment by briangow** [comment]
Thanks @tompollard! I've created a PR to update the `requirements.txt` package versions: https://github.com/ahli-org/chil-website/pull/203 .
