### ISSUE TITLE
Stop RocketChat from stealing cursor

### ISSUE THREAD

**Issue by tnaumann** [ahli-org/chil-website#73]
Currently when navigating to any of the keynote / tutorial / paper pages that have an embedded RocketChat, the cursor is grabbed by RocketChat and the page scrolls down past the other content. Would be nice if this did not happen.

**Comment by corcra** [comment]
Not sure how to fix this, but for what it's worth it only happens if you're logged in.

**Comment by tnaumann** [comment]
Definitely just a nice-to-have. I couldn't figure out how to get it either.
