### ISSUE TITLE
Rename organization and repo

### ISSUE THREAD

**Issue by tnaumann** [ahli-org/chil-website#98]
Start an "ahli" organization to house ahli.cc as well as the various associated repos for conferences (e.g. chil-website) and symposia (e.g. ml4health-website) under that organization.

**Comment by tompollard** [comment]
@tnaumann I should be able to switch the name of this one if that would help? This seems cleaner than setting up a new one and avoids having to reapply for the educational discount. I can add new admin etc if you send me the details.

**Comment by tnaumann** [comment]
Thanks, @tompollard! I think the outstanding question is what we should name it and whether ML4H would want to migrate to the new organization as well. I.e., we could `s/acm/ahli/`, but we might want to rename the org to something entirely different if it's intended to house both [chil-website](https://github.com/acm-chil/acm-chil-website) and [ml4health.github.io](https://github.com/ml4health/ml4health.github.io).

**Comment by tompollard** [comment]
Okay cool, definitely possible to rename the organisation once the name is settled. Just checked and @tnaumann is an owner of the organisation, so you are able to make updates directly.

**Comment by corcra** [comment]
Just following up on this - changing `ahli-chil` to `ahli` as the entity name makes sense to me, then we can have `ml4h-website` etc. in future. This will also enable us to develop and share non-website things between the two events.

**Comment by tompollard** [comment]
@corcra https://github.com/ahli has dibs on ahli!

**Comment by corcra** [comment]
`ahli-org` and `ahli-cc` are still open!

**Comment by tnaumann** [comment]
I had previously created `ahli-org`. I've deleted the organization hoping that we could use the name for rename, but it looks like it's still blocked. From the documentation, it may remain blocked for 90 days. I've submitted a ticket to have the name made available immediately: https://support.github.com/ticket/personal/0/1420917 (I don't know if you can see this, but for my own reference).

First, very sorry! Second, I'm in favor of `ahli-org` between the two, but we could go with `ahli-cc` if this messes it up too much.

**Comment by tnaumann** [comment]
FYI I've now renamed `ahli-org` per offline discussion with @corcra.
